# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32f05fe5c9b67068f806b8bd6e6434faef4d62401776e50761575ef740b592f4c96a9b1552774d6bceb847a371f87ccd99235c9c14712433fb21bf4c441d424f

test:
  secret_key_base: 25eaf32137f575b4de997b41ccd231c26cc87a0155f732f04af5c1a5e321866029c56eabf7b45774fbebd0dc1284d8d8bb7377b4d5a385950087411bd59ca67e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
